{
    "name": "Sync Syscom",
    "version": "0.0.1",
    "summary": "Integración SYSCOM – Odoo",
    "category": "Sales",
    "author": "Sync Syscom",
    "license": "LGPL-3",
    "depends": ["base", "product", "stock", "sale"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/res_config_settings_view.xml",
        "views/syscom_category_views.xml",
        "views/syscom_brand_views.xml",
        "views/sync_log_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": False,
}
