{
    "name": "Sync Syscom",
    "version": "0.0.1",
    "summary": "Integración SYSCOM – Odoo",
    "category": "Sales",
    "author": "Sync Syscom",
    "license": "LGPL-3",
    "depends": ["base", "product", "stock", "sale", "website_sale"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/res_config_settings_view.xml",
        "data/res_partner.xml",
        "data/pricelist.xml",
        "data/stock_syscom.xml",
        "views/syscom_category_views.xml",
        "views/syscom_brand_views.xml",
        "views/syscom_product_views.xml",
        "views/publish_job_views.xml",
        "views/sync_job_views.xml",
        "views/cost_job_views.xml",
        "views/product_data_job_views.xml",
        "views/sync_log_views.xml",
        "views/menu.xml",
        "views/website_sale_product_stock.xml",
        "views/product_template_views.xml",
        "views/website_sale_cart_syscom_error.xml",
        "data/cron.xml",
    ],
    "installable": True,
    "application": True,
    "images": ["static/description/icon.png"],
}
